### ISSUE TITLE
Android: Fails to parse GPX from Strava

### ISSUE THREAD

**Issue by ajchellew** [jenetics/jpx#104] opened 2019-12-04 08:48 UTC
Downloaded GPX from Strava doesn't parse. 
[NYC.gpx.txt](https://github.com/jenetics/jpx/files/3920911/NYC.gpx.txt) (renamed to txt for github upload)

```
java.lang.IllegalStateException: Current state (SPACE) not START_ELEMENT, START_ELEMENT, END_ELEMENT or ENTITY_REFERENCE
        at com.bea.xml.stream.MXParser.throwIllegalState(MXParser.java:3849)
        at com.bea.xml.stream.MXParser.getLocalName(MXParser.java:1085)
        at com.bea.xml.stream.MXParser.require(MXParser.java:1244)
        at io.jenetics.jpx.XMLStreamReaderAdapter.require(XMLStreamReaderAdapter.java:77)
        at io.jenetics.jpx.ElemReader.read(XMLReader.java:591)
        at io.jenetics.jpx.GPX$Reader.read(GPX.java:1139)
        at io.jenetics.jpx.GPX$Reader.read(GPX.java:1164)
        at io.jenetics.jpx.GPX$Reader.read(GPX.java:1178)
        at io.jenetics.jpx.GPX$Reader.read(GPX.java:1191)
        at io.jenetics.jpx.GPX.read(GPX.java:2064)
```
It does however work in Google Earth.
![image](https://user-images.githubusercontent.com/17216760/70127116-4c469b80-1672-11ea-906c-6751ec15e75a.png)

This is a virtual ride that includes power data. A real route without also doesn't parse but includes actual people's homes so sharing this one.

**Comment by jenetics** [comment] 2019-12-04 10:01
Are you using the latest version (1.6.0) of the library? I tested it on the master branch and it worked. This error seems to be fixed with #82.

**Comment by ajchellew** [comment] 2019-12-04 10:18
Yes `implementation 'io.jenetics:jpx:1.6.0'`

Should have added this is on Android.

Anything I can do to provide more detailed logs?

**Comment by jenetics** [comment] 2019-12-04 11:32
I haven't the possibility to test it on Android. Maybe you have to change the STAX library. #76 listed a Gradle configuration which seems to work.

**Comment by ajchellew** [comment] 2019-12-04 13:03
Yes we already included this. without the stax dependency JPX doesn't work at all.

```
    implementation 'stax:stax:1.2.0'
    implementation 'io.jenetics:jpx:1.6.0'
```
Understood its different on Android. We will have to investigate building/debugging from source.

**Comment by Segelzwerg** [comment] 2019-12-05 20:18
I can reproduce the error, but couldn't fix it. The most common solution I found was:
https://stackoverflow.com/a/47371517

```
implementation group: 'javax.xml.stream', name: 'stax-api', version: '1.0-2'
```

but this is from 2008 and most probably outdated, although suggested it in 2017. However these does not help much, because there is a new error:
```
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLInputFactory;
        at io.jenetics.jpx.GPX$Reader.read(GPX.java:1133)
        at io.jenetics.jpx.GPX.read(GPX.java:1984)
```

**Comment by tonsV2** [comment] 2020-05-15 16:40
@Segelzwerg - Maybe my comment [here](https://github.com/jenetics/jpx/issues/76#issuecomment-628623532) can help?

**Comment by Segelzwerg** [comment] 2020-05-18 18:34
@tonsV2 sorry for not getting back to you sooner. I have to reinstall the environment and will come back to you as soon as I tested it.

**Comment by Segelzwerg** [comment] 2020-05-18 19:51
@tonsV2 I actually ran into some trouble testing it. But I think it is due to I'm not being able to install Java 11 with Android Studio.

```console
error: cannot access GPX
import io.jenetics.jpx.GPX;
                      ^
  bad class file: /home/marcel/.gradle/caches/transforms-2/files-2.1/a6bd7189bc27fd2363528ef91ed73186/jetified-jpx-2.0.0.jar(io/jenetics/jpx/GPX.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by tonsV2** [comment] 2020-05-19 02:24
@Segelzwerg - Yes, I had similar errors due to libraries compiled with Java 11.

**Comment by Segelzwerg** [comment] 2020-05-19 06:20
@tonsV2 did you manage to fix them?

**Comment by tonsV2** [comment] 2020-05-19 06:47
The library was my own so I just recompiled with Java 8.

**Comment by tonsV2** [comment] 2020-05-19 15:33
@Segelzwerg - The project I've been using JPX in is [this](https://github.com/tonsV2/open-run-tracker). Maybe you can find some inspiration from that.

**Closed** 2021-11-12 14:55 UTC
Labels: question

**Comment by moiatto** [comment] 2023-02-16 09:22
Has anyone found a solution?
better if for last v3.0.1 ? 

i have tried as described in this thread, plus #76....same issues as above.

I have gradle 7.5 and I used Java 11, Java 17, Java 18 and Java 19.
