### ISSUE TITLE
XMLStreamException: Unexpected element <extensions>

### ISSUE THREAD

**Issue by dghelprat** [jenetics/jpx#57] opened 2018-02-27 09:31 UTC
When I try to parse files like the one in [test.gpx.zip](https://github.com/jenetics/jpx/files/1761977/test.gpx.zip), the following exception occurs:
```
java.io.IOException: javax.xml.stream.XMLStreamException
: Unexpected element <extensions>.
	at io.jenetics.jpx.GPX.read(GPX.java:1190)
	at io.jenetics.jpx.GPX.read(GPX.java:1204)
	at [...].main(Main.java:37)
Caused by: javax.xml.stream.XMLStreamException: Unexpected element <extensions>.
	at io.jenetics.jpx.ElemReader.read(XMLReader.java:529)
	at io.jenetics.jpx.ListReader.read(XMLReader.java:435)
	at io.jenetics.jpx.ListReader.read(XMLReader.java:421)
	at io.jenetics.jpx.ElemReader.throwUnexpectedElement(XMLReader.java:596)
	at io.jenetics.jpx.ElemReader.read(XMLReader.java:540)
	at io.jenetics.jpx.GPX.read(GPX.java:1185)
	... 4 more
```
According to specification, the tag \<extensions\> is valid in both \<trk\> and \<trkpt\> (which are the failing cases in this test), among other places.

**Comment by dghelprat** [comment] 2018-02-27 10:51
More specifically, the problem resides in having to force `GPX.read(input,true)` as the default for `GPX.read(input)` does not conform to [standard](http://www.topografix.com/gpx/1/1/#type_trkType).

**Comment by jenetics** [comment] 2018-02-28 15:50
You are right, but the solution would be to ignore the `extensions` element by default. Since this XML element can contain arbitrary data, there is no way to generically store this data.

**Comment by jenetics** [comment] 2018-03-01 20:04
Merged into r1.3.0 branch.

**Closed by jenetics** 2018-03-01 20:04 UTC
Labels: bug, enhancement

**Comment by ryanthara** [comment] 2019-07-22 19:16
I test some normal Garmin eTrex10 files here and can reproduce the `IOException` like the way @dghelprat did. The files are exported with different kind of Garmin firmware versions I used over the last three years to export GPX files.

`java.io.IOException: javax.xml.stream.XMLStreamException: Unexpected element <trkpt>.
	at io.jenetics.jpx.GPX$Reader.read(GPX.java:1143)
	at io.jenetics.jpx.GPX$Reader.read(GPX.java:1160)
	at io.jenetics.jpx.GPX$Reader.read(GPX.java:1174)
	at io.jenetics.jpx.GPX$Reader.read(GPX.java:1187)
	at io.jenetics.jpx.GPX.read(GPX.java:2054)`

Should I open a new issue @jenetics?

**Comment by jenetics** [comment] 2019-07-22 19:18
Yes, please, open a new issue with the file(s) that causes the error.
